name: Cron job to delete ended Jobs

on:
  schedule: # "At 06:00 PM, only on Monday"
    - cron: "0 18 * * 1"

jobs:
  deleteJobs:
    runs-on: ubuntu-latest
    steps:
      - name: Call the delete api
        run: |
          curl -X POST https://zjunior.com/api/cleanJobs -H "auth: ${{ secrets.DEL_TOKEN }}"
          
