name: Cron job to Update the SSG by redeploing

on:
  workflow_dispatch:
  schedule: # "At 06:00 AM everyday"
    - cron: "0 6 * * *"

jobs:
  Update-ssg:
    runs-on: ubuntu-latest
    steps:
      - name: Call the webhook
        run: |
          response=$(curl -X POST ${{ secrets.WEBHOOK }} | grep '"success": true')
          if [[ response ]]
          then
          echo "done"
          exit 0
          else echo "fail" exit 1;
          fi
